name    'cq5'
version '0.0.1'
source 'git://github.com/dailybeast/puppet/modules/cq5'
author 'The Newsweek/Daily Beast Company LLC'
license 'Apache License, Version 2'
summary 'Manages cq5 packages, services, configs for cq5'
description 'Manages cq5 packages, services, configs for cq5'

## Add dependencies, if any:
dependency 'puppetlabs/stdlib', '>= 2.2.1'
