name    'logwatch'
version '0.0.1'
source 'git://github.com/dailybeast/puppet/modules/logwatch'
author 'The Newsweek/Daily Beast Company LLC'
license 'Apache License, Version 2'
summary 'Manages logwatch packages, configs and services'
description 'Manages logwatch packages, configs and services'

## Add dependencies, if any:
dependency 'puppetlabs/stdlib', '>= 2.2.1'
