name    'sudo'
version '0.0.1'
source 'git://github.com/dailybeast/puppet/modules/sudo'
author 'The Newsweek/Daily Beast Company LLC'
license 'Apache License, Version 2'
summary 'Manages sudo and sudoers on a system'
description 'Manages sudo on a system'

## Add dependencies, if any:
dependency 'puppetlabs/stdlib', '>= 2.2.1'
