name    'nw_analytics'
version '0.0.1'
source 'git://github.com/dailybeast/puppet/modules/nw_analytics'
author 'The Newsweek/Daily Beast Company LLC'
license 'Apache License, Version 2'
summary 'Manages nw_analytics packages, services, configs for nw_analytics'
description 'Manages nw_analytics packages, services, configs for nw_analytics'

## Add dependencies, if any:
dependency 'puppetlabs/stdlib', '>= 2.2.1'
