name    'w3pw'
version '0.0.1'
source 'git://github.com/dailybeast/puppet/modules/w3pw'
author 'The Newsweek/Daily Beast Company LLC'
license 'Apache License, Version 2'
summary 'Manages w3pw packages, services, configs for w3pw'
description 'Manages w3pw packages, services, configs for w3pw'

## Add dependencies, if any:
dependency 'puppetlabs/stdlib', '>= 2.2.1'
