name    'cron'
version '0.0.1'
source 'git://github.com/dailybeast/puppet/modules/cron'
author 'The Newsweek/Daily Beast Company LLC'
license 'Apache License, Version 2'
summary 'Manages cron packages, services, configs for cron'
description 'Manages cron packages, services, configs for cron'

## Add dependencies, if any:
dependency 'puppetlabs/stdlib', '>= 2.2.1'
