name    'ntp'
version '0.0.1'
source 'git://github.com/dailybeast/puppet/modules/ntp'
author 'The Newsweek/Daily Beast Company LLC'
license 'Apache License, Version 2'
summary 'Manages ntp packages, services, configs for ntp'
description 'Manages ntp packages, services, configs for ntp'

## Add dependencies, if any:
dependency 'puppetlabs/stdlib', '>= 2.2.1'
