name    'perl'
version '0.0.1'
source 'git://github.com/dailybeast/puppet/modules/perl'
author 'The Newsweek/Daily Beast Company LLC'
license 'Apache License, Version 2'
summary 'Manages perl packages'
description 'Manages perl packages'

## Add dependencies, if any:
dependency 'puppetlabs/stdlib', '>= 2.2.1'
