name    'postfix'
version '0.0.1'
source 'git://github.com/dailybeast/puppet/modules/postfix'
author 'The Newsweek/Daily Beast Company LLC'
license 'Apache License, Version 2'
summary 'Manages postfix packages, services, configs for postfix'
description 'Manages postfix packages, services, configs for postfix'

## Add dependencies, if any:
dependency 'puppetlabs/stdlib', '>= 2.2.1'
