name    'activemq'
version '0.0.1'
source 'git://github.com/dailybeast/puppet/modules/activemq'
author 'The Newsweek/Daily Beast Company LLC'
license 'Apache License, Version 2'
summary 'Manages activemq packages, services, configs for activemq'
description 'Manages activemq packages, services, configs for activemq'

## Add dependencies, if any:
dependency 'puppetlabs/stdlib', '>= 2.2.1'
