name    'jetty'
version '0.0.1'
source 'git://github.com/dailybeast/puppet/modules/jetty'
author 'The Newsweek/Daily Beast Company LLC'
license 'Apache License, Version 2'
summary 'Manages jetty packages, services, configs for jetty'
description 'Manages jetty packages, services, configs for jetty'

## Add dependencies, if any:
dependency 'puppetlabs/stdlib', '>= 2.2.1'
