name    'puppet'
version '0.0.1'
source 'git://github.com/dailybeast/puppet/modules/puppet'
author 'The Newsweek/Daily Beast Company LLC'
license 'Apache License, Version 2'
summary 'Manages puppet packages, mongdb ppa's, and configs'
description 'Manages puppet packages, puppet ppa's, and configs'

## Add dependencies, if any:
dependency 'puppetlabs/stdlib', '>= 2.2.1'
