name    's3cmd'
version '0.0.1'
source 'git://github.com/dailybeast/puppet/modules/s3cmd'
author 'The Newsweek/Daily Beast Company LLC'
license 'Apache License, Version 2'
summary 'Manages s3cmd packages and configs'
description 'Manages s3cmd packages and configs'

## Add dependencies, if any:
dependency 'puppetlabs/stdlib', '>= 2.2.1'
