name    'users'
version '0.0.1'
source 'git://github.com/dailybeast/puppet/modules/users'
author 'The Newsweek/Daily Beast Company LLC'
license 'Apache License, Version 2'
summary 'Manages users, groups, and ssh keys on a system'
description 'Manages accounts on a system'

## Add dependencies, if any:
dependency 'puppetlabs/stdlib', '>= 2.2.1'
