name    'ruby'
version '0.0.1'
source 'git://github.com/dailybeast/puppet/modules/ruby'
author 'The Newsweek/Daily Beast Company LLC'
license 'Apache License, Version 2'
summary 'Manages ruby packages, both gem and apt'
description 'Manages ruby packages, both gem and apt'

## Add dependencies, if any:
dependency 'puppetlabs/stdlib', '>= 2.2.1'
