name    'vsftpd'
version '0.0.1'
source 'git://github.com/dailybeast/puppet/modules/vsftpd'
author 'The Newsweek/Daily Beast Company LLC'
license 'Apache License, Version 2'
summary 'Manages vsftpd packages, services, configs for vsftpd'
description 'Manages vsftpd packages, services, configs for vsftpd'

## Add dependencies, if any:
dependency 'puppetlabs/stdlib', '>= 2.2.1'
