name    'rsyslog'
version '0.0.1'
source 'git://github.com/dailybeast/puppet/modules/rsyslog'
author 'The Newsweek/Daily Beast Company LLC'
license 'Apache License, Version 2'
summary 'Manages rsyslog packages, services, configs for rsyslog'
description 'Manages rsyslog packages, services, configs for rsyslog'

## Add dependencies, if any:
dependency 'puppetlabs/stdlib', '>= 2.2.1'
