Feature: apache/config.pp
  In order to manage apache services on a system. This define must take a hash of
  configs to install and create them.

    Scenario: apache::config default
    Given a node named "apache-config-default"
    When I compile the catalog
    Then compilation should succeed
    And all resource dependencies should resolve
    And file "/etc/apache2/apache2.conf" should be "present"
      And the file should contain /^#ServerRoot "/etc/apache2"/
      And the file should contain "LockFile ${APACHE_LOCK_DIR}/accept.lock"
      And the file should contain "Timeout 300"
      And the file should contain "KeepAlive Off"
      And the file should contain "MaxKeepAliveRequests 100"
      And the file should contain "KeepAliveTimeout 5"
      And the file should contain "    StartServers          5"
      And the file should contain "    MinSpareServers       5"
      And the file should contain "    MaxSpareServers      10"
      And the file should contain "    MaxClients          150"
      And the file should contain "    MaxRequestsPerChild   0"
      And the file should contain "    StartServers          2"
      And the file should contain "    MinSpareThreads      25"
      And the file should contain "    MaxSpareThreads      75"
      And the file should contain "    ThreadLimit          64"
      And the file should contain "    ThreadsPerChild      25"
      And the file should contain "    MaxClients          150"
      And the file should contain "    MaxRequestsPerChild   0"
      And the file should contain "    StartServers          2"
      And the file should contain "    MinSpareThreads      25"
      And the file should contain "    MaxSpareThreads      75"
      And the file should contain "    ThreadLimit          64"
      And the file should contain "    ThreadsPerChild      25"
      And the file should contain "    MaxClients          150"
      And the file should contain "    MaxRequestsPerChild   0"
      And the file should contain "DefaultType None"
      And the file should contain "HostnameLookups Off"
      And the file should contain "ErrorLog ${APACHE_LOG_DIR}/error.log"
      And the file should contain "LogLevel warn"
    And file "/etc/apache2/envvars" should be "present"
      And the file should contain "export APACHE_RUN_USER=www-data"
      And the file should contain "export APACHE_RUN_GROUP=www-data"
      And the file should contain "export APACHE_PID_FILE=/var/run/apache2$SUFFIX.pid"
      And the file should contain "export APACHE_RUN_DIR=/var/run/apache2$SUFFIX"
      And the file should contain "export APACHE_LOCK_DIR=/var/lock/apache2$SUFFIX"
      And the file should contain "export APACHE_LOG_DIR=/var/log/apache2$SUFFIX"
      And the file should contain "export LANG=C"
      And the file should contain "#. /etc/default/locale"
      And the file should contain "#export APACHE_LYNX='www-browser -dump'"
      And the file should contain "#APACHE_ULIMIT_MAX_FILES='ulimit -n 65536'"
    And file "/etc/default/apache2" should be "present"
      And the file should contain "HTCACHECLEAN_RUN=auto"
      And the file should contain "HTCACHECLEAN_MODE=daemon"
      And the file should contain "HTCACHECLEAN_SIZE=300M"
      And the file should contain "HTCACHECLEAN_DAEMON_INTERVAL=120"
      And the file should contain "HTCACHECLEAN_PATH=/var/cache/apache2/mod_disk_cache"
      And the file should contain /^HTCACHECLEAN_OPTIONS="-n"/
    And file "/etc/apache2/conf.d/security" should be "present"
      And the file should contain /^#<Directory \/>$/
      And the file should contain /^#  AllowOverride None$/
      And the file should contain /^#  Order Deny,Allow$/
      And the file should contain /^#  Deny from all$/
      And the file should contain /^#<\/Directory>$/
      And the file should contain "ServerTokens OS"
      And the file should contain "ServerSignature Off"
      And the file should contain "TraceEnable Off"
    And file "/etc/apache2/conf.d/charset" should be "present"
      And the file should contain "#AddDefaultCharset UTF-8"
    And file "/etc/apache2/conf.d/host_logging" should be "present"
      And the file should contain /LogFormat "%!418\{Host\}i %h %l %u %t \\\"%r\\\" %>s %O \\\"%!418\{Referer\}i\\\" \\\"%!418\{User-Agent\}i\\\"" host_header_combined/
    And file "/etc/logrotate.d/apache2" should be "present"
      And the file should contain "/var/log/apache2/*.log {"

    Scenario: apache::config from facts
    Given a node named "apache-config-default"
    And a fact "apache_server_root" of "/etc/httpd"
    And a fact "apache_lock_file" of "apache.lock"
    And a fact "apache_timeout" of "600"
    And a fact "apache_keepalive" of "On"
    And a fact "apache_max_keep_alive_requests" of "200"
    And a fact "apache_keep_alive_timeout" of "10"
    And a fact "apache_prefork_start_servers" of "10"
    And a fact "apache_prefork_min_spare_servers" of "10"
    And a fact "apache_prefork_max_spare_servers" of "20"
    And a fact "apache_prefork_max_clients" of "400"
    And a fact "apache_prefork_max_requests_per_child" of "1000"
    And a fact "apache_worker_start_servers" of "5"
    And a fact "apache_worker_min_spare_threads" of "50"
    And a fact "apache_worker_max_spare_threads" of "100"
    And a fact "apache_worker_thread_limit" of "200"
    And a fact "apache_worker_threads_per_child" of "50"
    And a fact "apache_worker_max_clients" of "400"
    And a fact "apache_worker_max_requests_per_child" of "1000"
    And a fact "apache_event_start_servers" of "5"
    And a fact "apache_event_min_spare_threads" of "100"
    And a fact "apache_event_max_spare_threads" of "200"
    And a fact "apache_event_thread_limit" of "400"
    And a fact "apache_event_threads_per_child" of "1000"
    And a fact "apache_event_max_clients" of "800"
    And a fact "apache_event_max_requests_per_child" of "2000"
    And a fact "apache_default_type" of "text/plain"
    And a fact "apache_hostname_lookups" of "On"
    And a fact "apache_default_error_log" of "default-error.log"
    And a fact "apache_log_level" of "debug"
    And a fact "apache_htcacheclean_run" of "yes"
    And a fact "apache_htcacheclean_mode" of "cron"
    And a fact "apache_htcacheclean_size" of "400M"
    And a fact "apache_htcacheclean_daemon_interval" of "180"
    And a fact "apache_htcacheclean_path" of "/tmp/mod_disk_cache"
    And a fact "apache_htcacheclean_options" of "-t"
    And a fact "apache_run_user" of "apache"
    And a fact "apache_run_group" of "apache"
    And a fact "apache_pid_file" of "/tmp/run/apache/httpd.pid"
    And a fact "apache_run_dir" of "/tmp/run/apache"
    And a fact "apache_lock_dir" of "/tmp/lock/apache"
    And a fact "apache_log_dir" of "/mnt/log/apache"
    And a fact "apache_env_lang" of "UTF-8"
    And a fact "apache_use_system_locale" of "yes"
    And a fact "apache_status_command" of "www-browser -dump"
    And a fact "apache_max_files" of "65535"
    And a fact "apache_disable_root_fs_access" of "true"
    And a fact "apache_server_tokens" of "Full"
    And a fact "apache_server_signature" of "On"
    And a fact "apache_trace_enable" of "yes"
    And a fact "apache_default_charset" of "FOO-CHARSET"
    When I compile the catalog
    Then compilation should succeed
    And all resource dependencies should resolve
    And file "/etc/apache2/apache2.conf" should be "present"
      And the file should contain /^ServerRoot "/etc/httpd"/
      And the file should contain "LockFile ${APACHE_LOCK_DIR}/apache.lock"
      And the file should contain "Timeout 600"
      And the file should contain "KeepAlive On"
      And the file should contain "MaxKeepAliveRequests 200"
      And the file should contain "KeepAliveTimeout 10"
      And the file should contain "    StartServers          10"
      And the file should contain "    MinSpareServers       10"
      And the file should contain "    MaxSpareServers       20"
      And the file should contain "    MaxClients            400"
      And the file should contain "    MaxRequestsPerChild   1000"
      And the file should contain "    StartServers          5"
      And the file should contain "    MinSpareThreads       50"
      And the file should contain "    MaxSpareThreads       100"
      And the file should contain "    ThreadLimit           200"
      And the file should contain "    ThreadsPerChild       50"
      And the file should contain "    MaxClients            400"
      And the file should contain "    MaxRequestsPerChild   1000"
      And the file should contain "    StartServers          5"
      And the file should contain "    MinSpareThreads       100"
      And the file should contain "    MaxSpareThreads       200"
      And the file should contain "    ThreadLimit           400"
      And the file should contain "    ThreadsPerChild       1000"
      And the file should contain "    MaxClients            800"
      And the file should contain "    MaxRequestsPerChild   2000"
      And the file should contain "DefaultType text/plain"
      And the file should contain "HostnameLookups On"
      And the file should contain "ErrorLog ${APACHE_LOG_DIR}/default-error.log"
      And the file should contain "LogLevel debug"
    And file "/etc/apache2/envvars" should be "present"
      And the file should contain "export APACHE_RUN_USER=apache"
      And the file should contain "export APACHE_RUN_GROUP=apache"
      And the file should contain "export APACHE_PID_FILE=/tmp/run/apache/httpd.pid"
      And the file should contain "export APACHE_RUN_DIR=/tmp/run/apache"
      And the file should contain "export APACHE_LOCK_DIR=/tmp/lock/apache"
      And the file should contain "export APACHE_LOG_DIR=/mnt/log/apache"
      And the file should contain "export LANG=UTF-8"
      And the file should contain ". /etc/default/locale"
      And the file should contain "export APACHE_LYNX='www-browser -dump'"
      And the file should contain "APACHE_ULIMIT_MAX_FILES='ulimit -n 65535'"
    And file "/etc/default/apache2" should be "present"
      And the file should contain "HTCACHECLEAN_RUN=yes"
      And the file should contain "HTCACHECLEAN_MODE=cron"
      And the file should contain "HTCACHECLEAN_SIZE=400M"
      And the file should contain "HTCACHECLEAN_DAEMON_INTERVAL=180"
      And the file should contain "HTCACHECLEAN_PATH=/tmp/mod_disk_cache"
      And the file should contain /^HTCACHECLEAN_OPTIONS="-t"/
    And file "/etc/apache2/conf.d/security" should be "present"
      And the file should contain /^<Directory \/>$/
      And the file should contain /^  AllowOverride None$/
      And the file should contain /^  Order Deny,Allow$/
      And the file should contain /^  Deny from all$/
      And the file should contain /^<\/Directory>$/
      And the file should contain "ServerTokens Full"
      And the file should contain "ServerSignature On"
      And the file should contain "TraceEnable On"
    And file "/etc/apache2/conf.d/charset" should be "present"
      And the file should contain "AddDefaultCharset FOO-CHARSET"
    And file "/etc/apache2/conf.d/host_logging" should be "present"
      And the file should contain /LogFormat "%!418\{Host\}i %h %l %u %t \\\"%r\\\" %>s %O \\\"%!418\{Referer\}i\\\" \\\"%!418\{User-Agent\}i\\\"" host_header_combined/
    And file "/etc/logrotate.d/apache2" should be "present"
      And the file should contain "/mnt/log/apache/*.log {"

    Scenario: apache::config no parameters
    Given a node named "apache-config-no-params"
    When I try to compile the catalog
    Then compilation should fail
