name    'shells'
version '0.0.1'
source 'git://github.com/dailybeast/puppet/modules/shells'
author 'The Newsweek/Daily Beast Company LLC'
license 'Apache License, Version 2'
summary 'Manages shells packages, services, configs for shells'
description 'Manages shells packages, services, configs for shells'

## Add dependencies, if any:
dependency 'puppetlabs/stdlib', '>= 2.2.1'
