name    'dhcp'
version '0.0.1'
source 'git://github.com/dailybeast/puppet/modules/dhcp'
author 'The Newsweek/Daily Beast Company LLC'
license 'Apache License, Version 2'
summary 'Manages dhcp packages, services, configs for dhcp'
description 'Manages dhcp packages, services, configs for dhcp'

## Add dependencies, if any:
dependency 'puppetlabs/stdlib', '>= 2.2.1'
