name    'aws'
version '0.0.1'
source 'git://github.com/dailybeast/puppet/modules/aws'
author 'The Newsweek/Daily Beast Company LLC'
license 'Apache License, Version 2'
summary 'Scripts, services, packages for managing AWS resources'
description 'Scripts, services, packages for managing AWS resources'

## Add dependencies, if any:
dependency 'puppetlabs/stdlib', '>= 2.2.1'
