name    'python'
version '0.0.1'
source 'git://github.com/dailybeast/puppet/modules/python'
author 'The Newsweek/Daily Beast Company LLC'
license 'Apache License, Version 2'
summary 'Manages python packages, both pip and apt'
description 'Manages python packages, both pip and apt'

## Add dependencies, if any:
dependency 'puppetlabs/stdlib', '>= 2.2.1'
