name    'hosts'
version '0.0.1'
source 'git://github.com/dailybeast/puppet/modules/hosts'
author 'The Newsweek/Daily Beast Company LLC'
license 'Apache License, Version 2'
summary 'Manages /etc/hosts file and host file entries on a system"
description 'Manages /etc/hosts file and host file entries on a system"

## Add dependencies, if any:
dependency 'puppetlabs/stdlib', '>= 2.2.1'
